### ISSUE TITLE
lists not shown on app-startup

### ISSUE THREAD

**Issue by Danfro** [kugiigi/talaan-app#11]
When starting the app my lists are not shown.
Steps to reproduce:
1. Start Talaan - main page does not show any lists
2. goto another page like favorites - your favorites are visible
3. go back to list view - all lists are visible
![step 1](https://user-images.githubusercontent.com/37637312/49673416-bb44e080-fa6e-11e8-998f-71ccbf146dc1.png)
![step 2](https://user-images.githubusercontent.com/37637312/49673419-bbdd7700-fa6e-11e8-9aa2-56144929748c.png)
![step 3](https://user-images.githubusercontent.com/37637312/49673420-bbdd7700-fa6e-11e8-8e7e-bf8758dfff94.png)

**Comment by kugiigi** [comment]
Hello, I know it's been almost a year...sorry :sweat_smile: 
but do you still encounter this because so far I can't replicate this.

Can you try something? because I probably stumbled upon the real bug that causes this.

1. Go to `Saved` or `History` page.
2. Select the `Favorites` tab
3. Go back to `Lists` page.
4. Close the app
5. Open the app.

In my tests, the `Favorites` tab of the `Saved` or `History` page is being displayed instead of `Lists`.

**Comment by Danfro** [comment]
Shame on me ;-) but I did not continue to use Talaan app. I haven't even got it installed anymore. Therefore I can't tell.

But because I almost certainly had no favourites added, that this (empty) page would have been displayed instead of `Lists`. That seems to be plausible as the source of this error.

**Comment by Danfro** [comment]
You may not know, but there is a redeveloping of notes app in progress. A new (core) app is going to be created. See [Memo app](https://gitlab.com/cibersheep/memo-app). @cibersheep is currently main driver of this project.

Just in case you would like to join the team or bring in ideas from Talaan app.

**Comment by kugiigi** [comment]
Okay, that's fine :smile: 
It's nice to see active development of the Notes app or whatever it'll be called now.
Good luck.
